version: 2
jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            docker build -t opengg/rust-wasm:latest .
            echo "$DOCKER_PASSWORD_BASE64"|base64 -d|docker login -u "$DOCKER_USER" --password-stdin
            docker tag opengg/rust-wasm:latest "opengg/rust-wasm:1.0.$CIRCLE_BUILD_NUM"
            docker push opengg/rust-wasm:latest
            docker push "opengg/rust-wasm:1.0.$CIRCLE_BUILD_NUM"
