version: 2
jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            docker build -t opengg/rust-wasm .
            echo "$DOCKER_PASSWORD_BASE64"|base64 -d|docker login -u "$DOCKER_USER" --password-stdin
            docker push opengg/rust-wasm

