version: 2
jobs:
  build:
    docker:
      - image: debian:stable

    steps:
      - checkout

      - run:
          name: Build and push Docker image
          command: |
            docker build -t opengg/rust-wasm .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push opengg/rust-wasm

