version: 2
jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            docker build -t opengg/rust-wasm:local .
            echo "$DOCKER_PASSWORD_BASE64"|base64 -d|docker login -u "$DOCKER_USER" --password-stdin
            DOCKER_BUILD_TAG="${CIRCLE_BRANCH}"
            DOCKER_BUILD_VERSION="1.0.${CIRCLE_BUILD_NUM}"
            if [ "${DOCKER_BUILD_TAG}" == "master" ]; then
              DOCKER_BUILD_TAG="latest"
            else
              DOCKER_BUILD_VERSION="${DOCKER_BUILD_TAG}-${DOCKER_BUILD_VERSION}"
            fi
            docker tag opengg/rust-wasm:local "opengg/rust-wasm:${DOCKER_BUILD_TAG}"
            docker tag opengg/rust-wasm:local "opengg/rust-wasm:${DOCKER_BUILD_VERSION}"
            docker push "opengg/rust-wasm:${DOCKER_BUILD_TAG}"
            docker push "opengg/rust-wasm:${DOCKER_BUILD_VERSION}"
